# Generated by Django 4.2.1 on 2023-07-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DForm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Sage',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Sname',
            new_name='name',
        ),
    ]
